# Generated by Django 4.1.3 on 2023-02-07 19:09

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="encoder",
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
