# Generated by Django 4.1.3 on 2023-02-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_mlmodel_selected_model_mlmodel_selected_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="accuracy",
            field=models.FloatField(null=True),
        ),
    ]
