# Generated by Django 4.1.3 on 2022-12-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_dataset_options_mlmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mlmodel",
            options={"verbose_name": "ML Model"},
        ),
    ]
